version: "3"

services:
  zookeeper:
    image: "zookeeper:3.8"
    container_name: "spekka_zookeeper"
    networks:
       - spekkatalk
       
    # volumes:
    #   - zookeeper_data:/data
    #   - zookeeper_logs:/datalogs


  kafka:
    image: "nyadesu/kafka-docker"
    container_name: "spekka_kafka"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=spekka_zookeeper.spekkatalk:2181
      - KAFKA_ADVERTISED_HOST_NAME=spekka_kafka.spekkatalk
      - KAFKA_CREATE_TOPICS=readings:3:1,counters:3:1
    networks:
      - spekkatalk

    # volumes:
    #   - kafka_data:/kafka

  cassandra:
    image: "cassandra:3.11"
    container_name: "spekka_cassandra"
    networks:
      - spekkatalk


networks:
  spekkatalk:
    external: true

# volumes:
#   zookeeper_data:
#   zookeeper_logs:
#   kafka_data: