version: "2.2"

services:
  zookeeper:
    image: "zookeeper:3.8"
    container_name: "spekka_zookeeper"
    networks:
       - spekkatalk
    environment:
       - ZK_SERVER_HEAP=512
       
    # volumes:
    #   - zookeeper_data:/data
    #   - zookeeper_logs:/datalogs


  kafka:
    #image: "nyadesu/kafka-docker" #ARM version of wurstmeister/kafka
    image: "wurstmeister/kafka:2.13-2.8.1"
    container_name: "spekka_kafka"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=spekka_zookeeper.spekkatalk:2181
      - KAFKA_ADVERTISED_HOST_NAME=spekka_kafka.spekkatalk
      - KAFKA_CREATE_TOPICS=readings:3:1,counters:3:1
      - KAFKA_OPTS=-Xmx1500M
    networks:
      - spekkatalk
    mem_limit: 2G

    # volumes:
    #   - kafka_data:/kafka

  cassandra:
    image: "cassandra:3.11"
    container_name: "spekka_cassandra"
    networks:
      - spekkatalk
    #mem_limit: 1G


networks:
  spekkatalk:
    external: true

# volumes:
#   zookeeper_data:
#   zookeeper_logs:
#   kafka_data: